### ISSUE TITLE
How to use this actions without providing GH_TOKEN env variable?

### ISSUE THREAD

**Issue by uchenily** [maximeverreault/setup-fmt#97]
this is my workflow file:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install fmt
        uses: maximeverreault/setup-fmt@v1.0.0
        id: install_fmt
        with:
          version: 9.1.0
```

and then I get a error when running this workflow:

```
Run maximeverreault/setup-fmt@v1.0.0
Fetching FMT version: 9.1.0 ...
/usr/bin/gh release download 9.1.0 --clobber -R fmtlib/fmt
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
  env:
    GH_TOKEN: ${{ github.token }}
Error: The process '/usr/bin/gh' failed with exit code 4
```

I can fix it by add this:

```yaml
        env:
          GH_TOKEN: ${{ github.token }}
```

but is there a better way to fix it? thanks!
