### ISSUE TITLE
permission denied error when downloading libfmt

### ISSUE THREAD

**Issue by uchenily** [maximeverreault/setup-fmt#98]
```yaml
      - name: Install fmt
        uses: maximeverreault/setup-fmt@v1.0.0
        id: install_fmt
        with:
          version: 9.1.0
          directory: /usr/local
        env:
          GH_TOKEN: ${{ github.token }}
```

```
Run maximeverreault/setup-fmt@v1.0.0
Fetching FMT version: 9.1.0 ...
/usr/bin/gh release download 9.1.0 --clobber -R fmtlib/fmt
open fmt-9.1.0.zip: permission denied
Error: The process '/usr/bin/gh' failed with exit code 1
```
